name: Bump Version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bump:
    # Skip if the last commit was created by a previous workflow run
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version
        run: |
          old=$(node -p "require('./package.json').version")
          npm version patch -m "chore: bump version %s [skip ci]"
          new=$(node -p "require('./package.json').version")
          echo "Bumped version $old -> $new" >> $GITHUB_STEP_SUMMARY

      - name: Push changes (commit + tag)
        run: |
          git push --follow-tags

